### PR TITLE
REST guidelines

### PR DESCRIPTION
**Pull request by oyron**

### CODE REVIEW

**Comment by mahewitt** [comment]
Not sure if this is the correct page to add it, but does Equinor have any thought on oData - https://www.odata.org/

**Comment by jonatanP1993** [comment]
After reading through the document, and the links in the document, I find the document very well structured and informative.

My only concern is how to enforce the guidelines, but that's a different discussion.

**Comment by oyron** [comment]
> Not sure if this is the correct page to add it, but does Equinor have any thought on oData - https://www.odata.org/

@mahewitt - I believe it is important that we build our REST APIs in a consistent way, to facilitate adoption and make building competence and doing reviews easier. Hence, we should choose one main approach for the APIs we build. The REST design guidelines are based on industry standard conventions for REST APIs. OData is a different flavor of REST, that we often encounter in products from Microsoft and SAP, but is generally less common in the industry. Choosing the most common/industry standard approach has less risk for Equinor, wrt competence, longevity, etc.
For out-of-the box APIs or in special cases like where the tooling provides the API, OData could be the best option. It is classified as _careful_ in TLC.

**Comment by oyron** [comment]
> Selve beskrivelsen av REST er jo grei, så dette er et bra tillegg til strategien.
> Jeg skulle likevel ønsket meg litt mer fokus på den synkrone naturen til HTTP (og dermed REST), i forhold til asynkrone mekanismer som man vil trenge i event drevne systemer. Jeg tror GraphQL er en bedre match med slike arkitekturer. Tror dette er et tema vi bør ta opp i kjernegruppen ved en senere anledning for å se hvordan vi kan inkludere det i strategien.

Absolutely agree that we should discuss GraphQL and async APIs and look into how we should include this in the strategy.

**Pull request merged**
